baseURL: "https://thinkingkuumba.com"
languageCode: en-us
title: Thinking Kuumba
summary: "A blog about the things I'm thinking about and the things I'm making."
image: "/images/kuumba.png"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
      main:
        - identifier: about
          name: "About"
          url: "/about/"
          weight: 5
params:
  social:
    image: "/default-social-image.jpg"
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  env: production
  copyright: "Copyright © 2024 MichaelBTech LLC."

  homeInfoParams:
    Title: "By Michael Brown"
    Content: "A blog about the things I'm thinking about and the things I'm making."

  socialIcons:
      - name: instagram
        url: "https://instagram.com/michaelbrwnjr"
      - name: threads
        url: "https://threads.net/michaelbrwnjr"
      - name: X
        url: "https://x.com/michaelabrownjr"
