baseURL: "https://www.MichaelBTech.com"
languageCode: en-us
title: MichaelBTech
summary: "A blog about the things I'm thinking about, the things I'm creating, and the things I'm seeing."
theme: ["PaperMod"]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
      main:
        - identifier: about
          name: "About"
          url: "/about/"
          weight: 5
        - identifier: search
          name: "Search"
          url: "/search/"
          weight: 10
        - identifier: posts
          name: "Posts"
          url: "/posts/"
          weight: 20

params:
  # social:
  #   image: "/default-social-image.jpg"
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  env: production
  copyright: "Copyright © 2024 MichaelBTech LLC."

homeInfoParams:
    Title: "By Michael Brown"
    Content: "A blog about the things I'm thinking about and the things I'm making."


  socialIcons:
      - name: instagram
        url: "https://instagram.com/michaelbtech"
      - name: threads
        url: "https://threads.net/michaelbtech"
      - name: github
        url: "https://github.com/michaelbrownjr"
      - name: linkedin
        url: "https://www.linkedin.com/in/michaelabrownjr/"

